### ISSUE TITLE
non jig code issue?

### ISSUE THREAD

**Issue by Raathmd** [runonbitcoin/sdk#3]
i added some code that is not extending a jig and the run framework goes into endless loop creating transactions.  

var xls = json2xls(Requestor);
  fs.writeFileSync(filename, xls, 'binary', (err) => {
     if (err) {
           console.log("writeFileSync :", err);
      }
    console.log( filename+" file is saved!");
 });

Requestor is the jig object.
This is running on the mock network.

**Comment by brentongunning** [comment]
Thanks Raathmd for opening an issue.

Would you mind posting the code for Requestor, and also for how you setup and use Run?

I wonder if json2xls is calling a method on Requester and creating transactions.

**Comment by Raathmd** [comment]
i am working on a delivery app to undercut uber eats ;-)

import Run from 'run-sdk';
import json2xls from 'json2xls';
const filename = 'sample.xlsx';
import fs from 'fs';
const run = new Run({ network: 'mock' });
//const run = new Run({purse: "", owner: ""})

class Requestor extends Jig {
    setDeliveryFee(value) {
      this.deliveryfee = value
    }
  }
  class Requests extends Jig {
    addRequestor(requestor) {
      this.requestor = [requestor];
    }
    addDriver(driver) {
      this.driver = [driver];
    }
  }

  class Driver extends Jig {
    init(){
      this.tokens = 50;
    }
    addTokens(value){
      this.tokens = this.tokens + value;
    }
    subtractTokens(value){
      this.tokens = this.tokens - value;
    }
    cashOutTokens(value){
      this.tokens = value;
    }
    setStatus(status){
      this.status = status;
    }
  }
  
  const requestor = new Requestor();
  const driver  = new Driver();
  const requests = new Requests();

  requests.addRequestor(requestor);
  requestor.setDeliveryFee('$30');

  requests.addDriver(driver);
  driver.setStatus('AcceptDelivery');
  if(driver.status === 'AcceptDelivery'){
  driver.subtractTokens(requestor.fee);
  }
  driver.setStatus('Delivered');
  if(driver.status === 'Delivered'){
    driver.addTokens(requestor.fee);
  }
  
  await run.sync()
  
  console.log(requestor.owner)
  console.log(requestor.location)
  console.log(requestor.origin)
  console.log(driver.status)

  var xls = json2xls(Requestor);
  fs.writeFileSync(filename, xls, 'binary', (err) => {
     if (err) {
           console.log("writeFileSync :", err);
      }
    console.log( filename+" file is saved!");
 });

**Comment by Raathmd** [comment]
Is node FS a method in the root class of JIG?
