### ISSUE TITLE
display token supply with decimal consideration in explorer

### ISSUE THREAD

**Issue by mboyd1** [runonbitcoin/sdk#6]
If a token uses decimals, the minted supply is an integer of [desired base supply] * [10^(number of decimals)]
this causes user confusion when viewing the token contract in the run explorer, as they think the total supply is much greater than the intended number.   It would be nice if the run jig explorer took token decimals into consideration when calculating the token supply for display.

**Comment by brentongunning** [comment]
This is a great idea, and in progress. Basically, the explorer is going to need specific views for specific types of jigs, and tokens are the place to start. Thanks for opening this @mboyd1.

**Comment by brentongunning** [comment]
The `amount` and `supply` properties are _decimalized_ in the Explorer.

We'll do custom views for different jig types down the road, but this should work for now.
